@apiKey = {{$dotenv FIREBASE_API_KEY}}
@email = {{$dotenv EMAIL}}
@password = {{$dotenv PASSWORD}}

@idToken = {{$dotenv ID_TOKEN}}
@localId = {{$dotenv LOCAL_ID}}


#################################
# LOGIN
#################################

###
# Sign in - Get token
POST https://identitytoolkit.googleapis.com/v1/accounts:signInWithPassword?key={{apiKey}}
Content-Type: application/json

{
  "email": "{{email}}",
  "password": "{{password}}",
  "returnSecureToken": true
}


#################################
# CREATE
#################################

###
# Sign up - Create user
POST https://identitytoolkit.googleapis.com/v1/accounts:signUp?key={{apiKey}}
Content-Type: application/json

{
  "email": "{{email}}",
  "password": "{{password}}",
  "returnSecureToken": true
}

#################################
# READ
#################################

###
# Get user information
POST https://identitytoolkit.googleapis.com/v1/accounts:lookup?key={{apiKey}}
Content-Type: application/json

{
  "idToken": "{{idToken}}"
}


#################################
# UPDATE
#################################

###
# Update email/password/profile
POST https://identitytoolkit.googleapis.com/v1/accounts:update?key={{apiKey}}
Content-Type: application/json

{
  "idToken": "{{idToken}}",
  "email": "newemail@example.com",
  "password": "newPassword123",
  "displayName": "Frank",
  "returnSecureToken": true
}


#################################
# DELETE
#################################

###
# Delete user account
POST https://identitytoolkit.googleapis.com/v1/accounts:delete?key={{apiKey}}
Content-Type: application/json

{
  "idToken": "{{idToken}}"
}