@projectId = {{$dotenv FIREBASE_PROJECT_ID}}
@apiKey = {{$dotenv FIREBASE_API_KEY}}
@email = {{$dotenv EMAIL}}
@password = {{$dotenv PASSWORD}}
@token = {{$dotenv TOKEN}}

###
# Sign up
POST https://identitytoolkit.googleapis.com/v1/accounts:signUp?key={{apiKey}}
Content-Type: application/json

{
  "email": "{{email}}",
  "password": "{{password}}",
  "returnSecureToken": true
}

###
# Sign in
POST https://identitytoolkit.googleapis.com/v1/accounts:signInWithPassword?key={{apiKey}}
Content-Type: application/json

{
  "email": "{{email}}",
  "password": "{{password}}",
  "returnSecureToken": true
}